Update service

diff --git a/service b/service
--- a/service
+++ b/service
@@ -6,10 +6,11 @@ CMDELSE=""
 PIDCMD=""
 PIDDIR="/data/data/com.termux/files/usr/var/run"
 LOGDIR="/data/data/com.termux/files/usr/var/log"
+ENABLE="/data/data/com.termux/files/usr/etc/service/enabled/"
 
 if [ -z $1 ]; then
    echo "This is a service manager writen by DebianLynx"
-   echo "Usage: service  $SERVICE_NAME  {start|stop|restart|status|log}"
+   echo "Usage: service  $SERVICE_NAME  {start|stop|restart|status|log|enable|disable}"
    exit
 fi
 #input the service info
@@ -22,7 +23,10 @@ fi
 
 PIDFILE="${PIDDIR}/${SERVICE_NAME}.pid"
 LOGFILE="${LOGDIR}/${SERVICE_NAME}.log"
+ENABLEFILE="/data/data/com.termux/files/usr/etc/service/enabled/${SERVICE_NAME}.sh"
 USEPIDCMD="${PIDCMD} ${PIDFILE}"
+ENABLECMD="service ${SERVICE_NAME} start"
+ASKYES="no"
 RETVAL=0
 PID=-1
 
@@ -95,7 +99,7 @@ ${CMD} ${USEPIDCMD} ${CMDELSE} >${LOGFILE} 2>&1 &
     # 检查pid file是否存在pid
     if [ -z $PID ] ; then
       echo "program is still writing PIDfile"
-	  echo "check later"
+      echo "check later"
       exit
     else
       # 检查pid对应的进程是否还存在
@@ -182,6 +186,39 @@ status() {
     echo "$SERVICE_NAME is not running"
   fi
 }
+
+enable() {
+  if [ -f $ENABLEFILE ]; then
+    echo "Areadly enabled"
+    exit
+  else
+    touch $ENABLEFILE
+    echo ${ENABLECMD} > ${ENABLEFILE}
+    chmod +x $ENABLEFILE
+    echo "start the ${SERVICE_NAME} now? "
+    read -p "start the ${SERVICE_NAME} now?:(yes/no)" ASKYES
+    if [ "${ASKYES}" = "yes" ]; then
+      start
+    else
+      exit
+    fi
+  fi
+  grep "bash /data/data/com.termux/files/usr/etc/service/enabled/*.sh" /data/data/com.termux/files/home/.bashrc > /dev/null
+  if [ $? -eq 0 ]; then
+    echo "check complate"
+  else
+    echo "bashrc error"
+fi
+}
+disable() {
+  if [ -f $ENABLEFILE ]; then
+    rm -f $ENABLEFILE
+    echo "Disabled"
+  else
+    echo "Disabled at the frist time"
+  fi
+}
+
 case "$2" in
   start)
     start
@@ -198,7 +235,13 @@ case "$2" in
   status)
     status
     ;;
+  enable)
+    enable
+    ;;    
+  disable)
+    disable
+    ;;
   *)
-    echo "Usage: service  $SERVICE_NAME  {start|stop|restart|status|log}"
+    echo "Usage: service  $SERVICE_NAME  {start|stop|restart|status|log|enable|disable}"
     ;;
 esac
